language: node_js
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
install:
- hexo generate
deploy:
  provider: s3
  access_key_id: AKIAJ3LNNWE5F4INDLIQ
  secret_access_key:
    secure: HgAKleJpKD/jkLNK9TVVXAK8b7OJ4GAwt/q2tBNqYeAIDUhBytROj71SajUGWKOzE9dPJl+ql7fO+TeSStOZm2UNNX48vx0CDQhoq7WkUDHROTkq88xLyQj1BQF4Dqd+wZknwAc/fvuRr5qC7Bqn9a4PN5bPv7uuTQ8WpnnSZ207UCAkjC5eAsLXkvVrLevXrbH2yZimae2FWj8EL4tcjvVWXeXbCpWifPaocwivBt5Wc1OyV3Wg/l2kbEhqFr9ArpWXixhr351Pla4g9wPj1g2vXVnQsasvbrFfi6yQDhkTXmI4x6sy0a5J/cN0ZYo9Oe0JrEW/buwm7oBI+iT7L5FKFN32lvkqD0Qo9Tvfk+elM3Rq5XCRaoKjbSrzQ4oj3pRaZ8gW3C8m4TCoKQ9s5PdmfoTR2T3LW7giK5JBEOKrVy1J+8i4MKQUV4Bos30j7Hp8qVUejAPPGvpp/nU3uVEBwxt3TjiFy2vQLI2OxKQ84y8o23yud/kfVkSdKuMXJsc0R2fchJBjJ35vOP3+1ZJXML8tGekUW/o+rfYsut6eyoquxQweD5fzxginEDXhRy0F1p3Rxj1VcAuDpNGWv85NY/7YyX7YmEfey/wuLYPXplj//i/br1XxKmgA1vK/jQhM/7ehYK3Ruu0suNr3PYPQdqOQea2uqfiE9B12V2g=
  bucket: kimjmin.net.test
  local-dir: public
  acl: ''
  on:
    repo: kimjmin/blog
